type User @table {
  displayName: String!
  email: String!
  createdAt: Timestamp!
  photoUrl: String
  bio: String
  jobTitle: String
  location: String
  linkedinUrl: String
  githubUrl: String
  personalWebsiteUrl: String
}

type Project @table {
  user: User
  title: String!
  description: String!
  createdAt: Timestamp!
  technologiesUsed: [String]
  liveDemoUrl: String
  repositoryUrl: String
  category: String
}

type ProjectImage @table {
  project: Project
  imageUrl: String!
  order: Int!
  caption: String
}

type Skill @table {
  user: User
  name: String!
  type: String!
  proficiency: String
}

type Experience @table {
  user: User
  companyName: String!
  jobTitle: String!
  startDate: Date!
  endDate: Date
  description: String
}

type Education @table {
  user: User
  institutionName: String!
  degree: String!
  major: String!
  startDate: Date!
  endDate: Date
  description: String
}